language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build
 
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"  
  - git add bundle.js
  - git commit --message "Travis build - 2"
  - git remote add origin-pages https://${GITHUB_TOKEN}@github.com/lordmancer/lm2-markets.git
  - git push --set-upstream origin-pages master