language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ${TRAVIS_BUILD_DIR}/docs
  target_branch: master
  on:
    branch: master
    